server:
  port: 8081

ai-backend:
  url: https://kdt-api-function.azurewebsites.net/api/v1/question?content=

solvedac:
  url: https://solved.ac/api/v3/user/top_100?handle=

askallen:
  #url: http://15.165.235.170/ai/allenapi
  url: http://localhost:8082/ai/allenapi

spring:
  application:
    name: algoy

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  mvc:
    hidden-method:
      filter:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/algoy?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - email
              - profile
upload:
  directory: uploads  # 업로드 파일이 저장될 경로